controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

idea_validate:
  path: /idea/{id}/validate
  controller: App\Controller\Ideas::validateIdea
  methods: [POST]

idea_refuse:
  path: /idea/{id}/refuse
  controller: App\Controller\Ideas::refusedIdea
  methods: [POST]

idea_archived:
  path: /idea/{id}/archived
  controller: App\Controller\Ideas::archivedIdea
  methods: [POST]

idea_delete:
  path: /idea/{id}/delete
  controller: App\Controller\Ideas::deleteIdea
  methods: [POST]

idea_wait_approve:
  path: /idea/{id}/wait
  controller: App\Controller\Ideas::waiting
  methods: [POST]

comment_delete:
  path: /idea/{id}/comment/{comment_id}/delete
  controller: App\Controller\Ideas::deleteComment
  methods: [POST]

idea_realized:
  path: /idea/{id}/idea_realized
  controller: App\Controller\Ideas::realizedIdea
  methods: [POST]

idea_not_realized:
  path: /idea/{id}/idea_not_realized
  controller: App\Controller\Ideas::notrealizedIdea
  methods: [POST]